-- 016: Site content CMS + blog posts table improvements
-- Run in Supabase Dashboard SQL Editor

-- ============================================
-- Site Content (CMS for marketing pages)
-- ============================================
create table if not exists site_content (
  id uuid primary key default gen_random_uuid(),
  page text not null,
  section text not null,
  content jsonb not null default '{}',
  sort_order int not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references users(id) on delete set null,
  unique(page, section)
);

alter table site_content enable row level security;

-- ============================================
-- Seed: Homepage content
-- ============================================
insert into site_content (page, section, content, sort_order) values
('homepage', 'hero', '{
  "dateline": "Social Intelligence",
  "dateline_sub": "For Creators Who Refuse to Be Average",
  "headline": "Stop Guessing.",
  "headline_highlight": "Start Growing.",
  "subheadline": "Go Virall is the social intelligence engine built for creators who refuse to be average. Real analytics. Real strategy. Real growth — across every platform.",
  "cta_primary": {"text": "Start Free", "href": "/signup"},
  "cta_secondary": {"text": "See How It Works", "href": "/#features"}
}'::jsonb, 0),

('homepage', 'stats', '[
  {"value": "7", "label": "Platforms Supported"},
  {"value": "0–100", "label": "Viral Score"},
  {"value": "4", "label": "AI Studio Tools"},
  {"value": "$0", "label": "Free Tier Price"}
]'::jsonb, 1),

('homepage', 'features', '[
  {"title": "Viral Score", "description": "AI-powered scoring that predicts how well your content will perform before you post.", "color": "#FF6B35", "href": "/compose"},
  {"title": "AI Strategist", "description": "Get personalized content ideas, captions, scripts, and bios generated by AI trained on viral patterns.", "color": "#7C3AED", "href": "/studio"},
  {"title": "Audience Intelligence", "description": "Deep analytics on who follows you, where they are, and what they engage with.", "color": "#0EA5E9", "href": "/audience"},
  {"title": "Deal Pipeline", "description": "Track brand deals, proposals, and revenue in one place. Know your worth.", "color": "#10B981", "href": "/revenue"},
  {"title": "Trend Detection", "description": "See what is trending across platforms before it peaks. Stay ahead of the algorithm.", "color": "#F59E0B", "href": "/studio/ideas"}
]'::jsonb, 2),

('homepage', 'how_it_works', '[
  {"step": "1", "title": "Connect", "description": "Link your social accounts. We never post on your behalf or store passwords."},
  {"step": "2", "title": "Analyze", "description": "Our AI analyzes your content, audience, and competitors across all platforms."},
  {"step": "3", "title": "Create & Ship", "description": "Use AI Studio to generate optimized content, then publish when your audience is most active."}
]'::jsonb, 3),

('homepage', 'pricing', '[
  {"name": "Free", "price": "$0", "tagline": "Everything you need to start", "features": ["7 platform connections", "Viral Score", "SMO Score", "Basic analytics", "AI Studio (limited)"], "cta_text": "Start Free", "cta_href": "/signup", "highlighted": false},
  {"name": "Creator", "price": "$29/mo", "tagline": "For creators ready to scale", "features": ["Everything in Free", "Unlimited AI Studio", "Audience Intelligence", "Deal Pipeline", "Priority support", "Advanced analytics"], "cta_text": "Go Creator", "cta_href": "/signup", "highlighted": true}
]'::jsonb, 4),

('homepage', 'footer', '{
  "headline": "Ready to go virall.",
  "description": "The social intelligence platform that transforms creators into cultural forces. Built on real data, tuned by real creators.",
  "contact_email": "info@donkeyideas.com",
  "offices": "NEW YORK · LOS ANGELES · LISBON"
}'::jsonb, 5),

('homepage', 'meta', '{
  "title": "Go Virall — Social Intelligence for Creators",
  "description": "The social intelligence engine built for creators. Real analytics, AI-powered strategy, and growth tools across 7 platforms.",
  "og_image": "/og-image.png"
}'::jsonb, 99)

on conflict (page, section) do nothing;

-- ============================================
-- Seed: About page content
-- ============================================
insert into site_content (page, section, content, sort_order) values
('about', 'hero', '{
  "headline": "About Go Virall.",
  "description": "Go Virall is the social intelligence platform built for creators who want to grow with data, not guesswork. We analyze your content across 7 platforms, score it with AI, and give you the tools to create content that actually performs."
}'::jsonb, 0),

('about', 'features', '[
  {"title": "Viral Score", "description": "AI-powered prediction of content performance before you post."},
  {"title": "AI Studio", "description": "Generate ideas, captions, scripts, and bios tuned to your niche."},
  {"title": "SMO Score", "description": "Social media optimization score across all connected platforms."},
  {"title": "Audience Intelligence", "description": "Deep analytics on your followers, demographics, and engagement patterns."},
  {"title": "Revenue Tracking", "description": "Track brand deals, proposals, and income in one dashboard."}
]'::jsonb, 1),

('about', 'contact', '{
  "email": "info@donkeyideas.com",
  "support_hours": "24 hours on business days"
}'::jsonb, 2)

on conflict (page, section) do nothing;

-- ============================================
-- Seed: FAQ content
-- ============================================
insert into site_content (page, section, content, sort_order) values
('faq', 'items', '[
  {"question": "What is Go Virall?", "answer": "Go Virall is a social intelligence platform for content creators. It connects to your social accounts, analyzes your content with AI, and gives you tools to grow your audience and revenue."},
  {"question": "Is Go Virall free?", "answer": "Yes. The free tier includes 7 platform connections, Viral Score, SMO Score, and basic analytics. The Creator plan ($29/mo) unlocks unlimited AI Studio, Audience Intelligence, and Deal Pipeline."},
  {"question": "What platforms do you support?", "answer": "Instagram, TikTok, YouTube, X (Twitter), LinkedIn, Facebook, and Twitch."},
  {"question": "How does the Viral Score work?", "answer": "Our AI analyzes your content against platform-specific engagement patterns, timing, hashtags, and audience behavior to predict performance on a 0-100 scale."},
  {"question": "What is the SMO Score?", "answer": "Social Media Optimization score. It measures how well-optimized your overall social presence is across all connected platforms — profile completeness, posting consistency, engagement rates, and growth velocity."},
  {"question": "How does the AI Studio work?", "answer": "AI Studio uses DeepSeek (with OpenAI, Anthropic, and Gemini as fallbacks) to generate content ideas, captions, video scripts, and bio suggestions personalized to your niche and audience."},
  {"question": "Do you store my social media passwords?", "answer": "No. We use official APIs and scraping with public data only. We never request or store your social media passwords."},
  {"question": "How do I cancel my subscription?", "answer": "Go to Settings > Billing > Manage Subscription. You can cancel anytime and keep access until the end of your billing period."},
  {"question": "Can I delete my account?", "answer": "Yes. Go to Settings > Account > Danger Zone > Delete Account. All your data will be permanently removed."},
  {"question": "Who provides the AI?", "answer": "We use DeepSeek as our primary AI provider, with automatic fallback to OpenAI, Anthropic (Claude), and Google Gemini if needed."}
]'::jsonb, 0)

on conflict (page, section) do nothing;

-- ============================================
-- Seed: Global content (shared across pages)
-- ============================================
insert into site_content (page, section, content, sort_order) values
('global', 'nav', '{
  "brand": "Go Virall",
  "items": [
    {"label": "Product", "href": "/#features"},
    {"label": "Intelligence", "href": "/about"},
    {"label": "Creators", "href": "/about"},
    {"label": "Pricing", "href": "/#pricing"},
    {"label": "Stories", "href": "/blog"}
  ]
}'::jsonb, 0),

('global', 'social_links', '{
  "twitter": "https://x.com/govirall",
  "instagram": "https://instagram.com/govirall",
  "tiktok": "https://tiktok.com/@govirall",
  "linkedin": "https://linkedin.com/company/govirall"
}'::jsonb, 1)

on conflict (page, section) do nothing;

-- ============================================
-- Indexes
-- ============================================
create index if not exists site_content_page_idx on site_content (page, sort_order);
